name: schedule
on:
  schedule:
    - cron: '0 0 20 * *'
  push:

env:
  CYPRESS_BASE_URL: ${{ secrets.CYPRESS_BASE_URL }}
  CYPRESS_COMPANY_ID: ${{ secrets.CYPRESS_COMPANY_ID }}
  CYPRESS_USERNAME: ${{ secrets.CYPRESS_USERNAME }}
  CYPRESS_PASSWORD: ${{ secrets.CYPRESS_PASSWORD }}

jobs:
  Run-Schedule:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: install dependencies
      - run: pnpm install
      - name: run tests
      - run: npx cypress run
